
runtime: python39
instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1

entrypoint: gunicorn -w 2 -b :$PORT "warp:create_app()"

handlers:
- url: /static
  static_dir: warp/static

- url: /.*
  script: auto
